trigger:
- master
- develop
- net5

stages:
- stage: Build
  jobs:
  - job: Build_Default
    displayName: Build Default
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: jobs/default-build.yml

- stage: Test
  jobs:
  - job: Test_Default
    displayName: Test Default
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: jobs/default-test.yml
